# -*- coding: utf-8 -*-
"""Mobile Price Classification ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsiZP4zeOaF_MCDHmn7TQKJsGbeSYvwX
"""

import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 1. Read the data
# Ensure the filename matches exactly what you uploaded
file_path = 'Mobile_Price_Classification-220531-204702.csv'
df = pd.read_csv(file_path)

# Features (all columns except price_range) and Target (price_range)
X = df.drop('price_range', axis=1)
y = df['price_range']

# 2. Split the data set (75% training, 25% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Feature Scaling (Important for Neural Networks)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 3. ANN model architecture
model = Sequential([
    # 1st hidden layer with 8 neurons
    Dense(8, activation='relu', input_dim=X_train.shape[1]),

    # 2nd hidden layer with 4 neurons
    Dense(4, activation='relu'),

    # Output layer (Sigmoid for binary classification: 0 or 1)
    Dense(1, activation='sigmoid')
])

# 4. Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 5. Fit and train the model
print("Starting training...")
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

# 6. Save the weights file
model.save_weights('mobile_price_weights.weights.h5')
print("\nSuccess! Weights saved as 'mobile_price_weights.weights.h5'")

